name: Bump version code & change version name

on:
  push:
    branches:
      - "master"

jobs:
  bump-version-and-open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract existing version code
        run: |
          # Get existing version code from build.gradle
          version_code=$(grep "versionCode" app/build.gradle | awk '{print $2}' | tr -d '\n')
          # Increment existing version code by 0.1
          new_version_code=$(echo "$version_code + 0.1" | bc)
          # Set environment variable for later use
          echo "NEW_VERSION_CODE=$new_version_code" >> $GITHUB_ENV

      - name: Increase version code and change version name
        run: |
          # Update build.gradle with new version code and name
          echo "$new_version_code - $new_version_code"
          sed -i "s|versionCode [0-9]\+|versionCode ${{ env.NEW_VERSION_CODE }}|g" app/build.gradle
          sed -i "s|versionName \"[^\"]*\"|versionName \"${{ env.NEW_VERSION_CODE }}\"|g" app/build.gradle

      - name: Commit and push changes
        run: |
          git config user.email "fazil8785@gmail.com"
          git config user.name "Mdmuzammil16"
          git commit -am "Bumping to ${{ env.NEW_VERSION_CODE }} version"
          git push origin HEAD
